src/Entity/AdjuntosPacientes.php
<?php

namespace App\Entity;

use App\Repository\AdjuntosPacientesRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AdjuntosPacientesRepository::class)
 */
class AdjuntosPacientes
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $id_paciente;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $url;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nombre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $tipo;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdPaciente(): ?string
    {
        return $this->id_paciente;
    }

    public function setIdPaciente(string $id_paciente): self
    {
        $this->id_paciente = $id_paciente;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(?string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getTipo(): ?string
    {
        return $this->tipo;
    }

    public function setTipo(string $tipo): self
    {
        $this->tipo = $tipo;

        return $this;
    }
}

src/Form/AdjuntosPacientesType.php
<?php

namespace App\Form;

use App\Entity\AdjuntosPacientes;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class AdjuntosPacientesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('id_paciente', HiddenType::class)
            ->add('nombre')
            ->add('tipo', ChoiceType::class, [
                'label' => 'Motivo de Egreso',
                'choices'  => [
                    'Seleccione una Tipo de Documento Adjunto' => 0,
                    'Documentación' => 1,
                    'Fotos Médicas' => 2,
                    'Administración' => 3,
                    'Informes y Recetas' => 4,
                    'Estudios' => 5,
                    'Otros' => 6,
                ]])
            ->add('archivoAdjunto', FileType::class, [
                'label' => 'Firma Digital (PDF file)',
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypes' => [
                            'application/pdf',
                            'application/x-pdf',
                        ],
                        'mimeTypesMessage' => 'Solo archivos con formato PDF son permitidos',
                    ])
                ],
            ])
            ->add('save', SubmitType::class, ['label' => 'Guardar', 'attr' => ['class' => 'btn-success']]);
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => AdjuntosPacientes::class,
        ]);
    }
}

src/Controller/AdjuntosPacientesController.php
<?php

namespace App\Controller;

use App\Entity\AdjuntosPacientes;
use App\Entity\Cliente;
use App\Form\AdjuntosPacientesType;
use App\Repository\AdjuntosPacientesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\ExtensionFileException;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

/**
 * @Route("/adjuntos/pacientes")
 */
class AdjuntosPacientesController extends AbstractController
{
    /**
     * @Route("/", name="adjuntos_pacientes_index", methods={"GET"})
     */
    public function index(AdjuntosPacientesRepository $adjuntosPacientesRepository): Response
    {
        return $this->render('adjuntos_pacientes/index.html.twig', [
            'adjuntos_pacientes' => $adjuntosPacientesRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new/{id}", name="adjuntos_pacientes_new", methods={"GET","POST"})
     */
    public function new(Request $request, Cliente $cliente, SluggerInterface $slugger, AdjuntosPacientesRepository $adjuntosPacientesRepository): Response
    {
        $adjuntosPaciente = new AdjuntosPacientes();
        $adjuntosPaciente->setIdPaciente($cliente->getId());

        $adjuntosActuales = $adjuntosPacientesRepository->findBy(array('id_paciente' => $cliente->getId()), array('tipo' => 'ASC'));

        $adjuntosArray = [];
        foreach ($adjuntosActuales as $adjunto) {
            $adjuntosArray[$adjunto->getTipo()][] = $adjunto;
        }

        //dd($adjuntosArray);

        $form = $this->createForm(AdjuntosPacientesType::class, $adjuntosPaciente);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();

            $archivoAdjunto = $form->get('archivoAdjunto')->getData();
            if ($archivoAdjunto) {
                $originalFilename = pathinfo($form->get('nombre')->getData(), PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$archivoAdjunto->guessExtension();
                $newPath = $this->getParameter('adjuntos_pacientes_directory') . '/' . $cliente->getId() . '/' . $form->get('tipo')->getData();

                try {
                    $archivoAdjunto->move(
                        $newPath,
                        $newFilename
                    );
                    $adjuntosPaciente->setUrl($newPath);
                } catch (FileException $e) {
                    throw new ExtensionFileException('Adjunto seleccionado no permitido. Intente con una Imagen o un PDF');
                }

                // updates the 'brochureFilename' property to store the PDF file name
                // instead of its contents
                $adjuntosPaciente->setUrl($newFilename);
            }

            $entityManager->persist($adjuntosPaciente);
            $entityManager->flush();

            return $this->redirectToRoute('adjuntos_pacientes_new',
                [
                    'id' => $cliente->getId(),
                ]);
        }

        return $this->render('adjuntos_pacientes/new.html.twig', [
            'adjuntos_paciente' => $adjuntosPaciente,
            'nombreCliente' => $cliente->getNombre(),
            'adjuntosActuales' => $adjuntosArray,
            'form' => $form->createView(),
            'cliente' => $cliente,
        ]);
    }

    /**
     * @Route("/{id}", name="adjuntos_pacientes_show", methods={"GET"})
     */
    public function show(AdjuntosPacientes $adjuntosPaciente): Response
    {
        return $this->render('adjuntos_pacientes/show.html.twig', [
            'adjuntos_paciente' => $adjuntosPaciente,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="adjuntos_pacientes_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, AdjuntosPacientes $adjuntosPaciente): Response
    {
        $form = $this->createForm(AdjuntosPacientesType::class, $adjuntosPaciente);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('adjuntos_pacientes_index');
        }

        return $this->render('adjuntos_pacientes/edit.html.twig', [
            'adjuntos_paciente' => $adjuntosPaciente,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="adjuntos_pacientes_delete", methods={"DELETE"})
     */
    public function delete(Request $request, AdjuntosPacientes $adjuntosPaciente): Response
    {
        if ($this->isCsrfTokenValid('delete'.$adjuntosPaciente->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($adjuntosPaciente);
            $entityManager->flush();
        }

        return $this->redirectToRoute('adjuntos_pacientes_index');
    }
}

templates/adjuntos_pacientes/_delete_form.html.twig
<form method="post" action="{{ path('adjuntos_pacientes_delete', {'id': adjuntos_paciente.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ adjuntos_paciente.id) }}">
    <button class="btn">Delete</button>
</form>

templates/adjuntos_pacientes/_form.html.twig
{{ form_start(form) }}
<br>
<div class="form-row">
    <div class="col-sm">
        {{ form_label(form.nombre, 'Nombre') }}
        {{ form_widget(form.nombre) }}
    </div>
</div>
<br>
<div class="form-row">
    <div class="col-sm">
        {{ form_label(form.tipo, 'Tipo de documento') }}
        {{ form_widget(form.tipo) }}
    </div>
</div>
<br><br>
<div class="form-row">
    <div class="col-sm">
        {{ form_label(form.archivoAdjunto, 'Adjuntar') }}
        {{ form_widget(form.archivoAdjunto) }}
    </div>
</div>
<br>
<br>
<div class="form-group">
    {{ form_widget(form.save, {'attr': {'class': 'btn btn-primary'}}) }}
    <a class="btn btn-default" href="{{ path('cliente_index') }}">volver</a>
</div>
<br>

{{ form_end(form) }}

templates/adjuntos_pacientes/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit AdjuntosPacientes{% endblock %}

{% block body %}
    <h1>Edit AdjuntosPacientes</h1>

    {{ include('adjuntos_pacientes/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('adjuntos_pacientes_index') }}">back to list</a>

    {{ include('adjuntos_pacientes/_delete_form.html.twig') }}
{% endblock %}

templates/adjuntos_pacientes/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}AdjuntosPacientes index{% endblock %}

{% block body %}
    <h1>AdjuntosPacientes index</h1>

    <table class="table table-responsive">
        <thead>
            <tr>
                <th>Id</th>
                <th>Id_paciente</th>
                <th>Url</th>
                <th>Nombre</th>
                <th>Tipo</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for adjuntos_paciente in adjuntos_pacientes %}
            <tr>
                <td>{{ adjuntos_paciente.id }}</td>
                <td>{{ adjuntos_paciente.idPaciente }}</td>
                <td>{{ adjuntos_paciente.url }}</td>
                <td>{{ adjuntos_paciente.nombre }}</td>
                <td>{{ adjuntos_paciente.tipo }}</td>
                <td>
                    <a href="{{ path('adjuntos_pacientes_show', {'id': adjuntos_paciente.id}) }}">show</a>
                    <a href="{{ path('adjuntos_pacientes_edit', {'id': adjuntos_paciente.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('adjuntos_pacientes_new') }}">Create new</a>
{% endblock %}

templates/adjuntos_pacientes/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nuevo Adjunto{% endblock %}

{% block body %}
    <h1>Nuevo Adjunto Para: {{ nombreCliente }}</h1>

    {{ include('adjuntos_pacientes/_form.html.twig') }}
{% endblock %}

templates/adjuntos_pacientes/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}AdjuntosPacientes{% endblock %}

{% block body %}
    <h1>AdjuntosPacientes</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ adjuntos_paciente.id }}</td>
            </tr>
            <tr>
                <th>Id_paciente</th>
                <td>{{ adjuntos_paciente.idPaciente }}</td>
            </tr>
            <tr>
                <th>Url</th>
                <td>{{ adjuntos_paciente.url }}</td>
            </tr>
            <tr>
                <th>Nombre</th>
                <td>{{ adjuntos_paciente.nombre }}</td>
            </tr>
            <tr>
                <th>Tipo</th>
                <td>{{ adjuntos_paciente.tipo }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('adjuntos_pacientes_index') }}">back to list</a>

    <a href="{{ path('adjuntos_pacientes_edit', {'id': adjuntos_paciente.id}) }}">edit</a>

    {{ include('adjuntos_pacientes/_delete_form.html.twig') }}
{% endblock %}