src/Entity/Evolucion.php
<?php

namespace App\Entity;

use App\Repository\EvolucionRepository;
use Doctrine\ORM\Mapping as ORM;
use App\Validator as AcmeAssert;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=EvolucionRepository::class)
 */
class Evolucion
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Cliente::class, inversedBy="evolucions")
     * @ORM\JoinColumn(nullable=false)
     *
     */
    private $paciente;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     * @AcmeAssert\EvolutionType
     */
    private $tipo;

    /**
     * @ORM\Column(type="datetime")
     */
    private $fecha;

    /**
     * @ORM\Column(type="text")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="array", nullable=true)
     */
    private $adjunto_url;

    public function __construct()
    {
        $this->adjunto_url = array();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPaciente(): ?Cliente
    {
        return $this->paciente;
    }

    public function setPaciente(?Cliente $paciente): self
    {
        $this->paciente = $paciente;

        return $this;
    }

    public function getTipo(): ?string
    {
        return $this->tipo;
    }

    public function setTipo(string $tipo): self
    {
        $this->tipo = $tipo;

        return $this;
    }

    public function getFecha(): ?\DateTimeInterface
    {
        return $this->fecha;
    }

    public function setFecha(\DateTimeInterface $fecha): self
    {
        $this->fecha = $fecha;

        return $this;
    }

    public function getUser(): ?string
    {
        return $this->user;
    }

    public function setUser(string $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getAdjuntoUrl()
    {
        if ($this->adjunto_url === null) {
            $this->adjunto_url = array();
        }
        return $this->adjunto_url;
    }

    public function setAdjuntoUrl(?array $adjunto_url): self
    {
        $this->adjunto_url = $adjunto_url;

        return $this;
    }

    public function addAdjuntoUrl(String $path): self
    {
        if (!array_search($path, $this->adjunto_url)) {
            $this->adjunto_url[] = $path;
        }

        return $this;
    }

    public function removeAdjuntoUrl(String $nombre, String $path): self
    {
        $clave = array_search($nombre, $this->adjunto_url);
        if ($clave !== false) {
            unset($this->adjunto_url[$clave]);
            $filePath = $path . $nombre;
            $filesystem = new Filesystem();
            if ($filesystem->exists($filePath)) {
                $filesystem->remove($filePath);
            }
        }

        return $this;
    }
}

src/Controller/EvolucionController.php
<?php

namespace App\Controller;

use http\Client;
use App\Entity\Doctor;
use App\Entity\Evolucion;
use App\Form\EvolucionType;
use App\Service\DoctorService;
use App\Repository\DoctorRepository;
use App\Repository\ClienteRepository;
use App\Repository\EvolucionRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Component\HttpFoundation\BinaryFileResponse;
use Symfony\Component\Validator\Validator\ValidatorInterface;
use Doctrine\DBAL\Exception\UniqueConstraintViolationException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\Validator\Exception\UnexpectedValueException;

/**
 * @Route("/evolucion")
 */
class EvolucionController extends AbstractController
{
    /**
     * @Route("/", name="evolucion_index", methods={"GET"})
     */
    public function index(Request $request, EvolucionRepository $evolucionRepository, ClienteRepository $clienteRepository, DoctorService $DoctorService): Response
    {
        $user               = $this->getUser();
        $tipoSeleccionado   = $request->query->get('tipoSeleccionado', 0);
        $limit              = $request->query->get('limit', 100);
        $currentPage        = $request->query->get('currentPage', 1);

        $f          = new \DateTime('first day of this month');
        $l          = new \DateTime('last day of this month');
        $from       = $request->get('from' , $f->format('Y-m-d'));
        $to         = $request->get('to', $l->format('Y-m-d'));  
        $fechaDesde = $from ? new \DateTime($from. '0:0:0') : $from;
        $fechaHasta = $to   ? new \DateTime($to. '23:59:59'): $to;

        $modalidades = [];
        if($user instanceOf Doctor) {
            $modalidades = $user->getModalidad();
        }

        if( count($modalidades) === 1 && $tipoSeleccionado === 0) {
            $tipoSeleccionado = $modalidades[0];
        }

        $clientId = $request->get('cliente');
        $cliente = $clienteRepository->find($clientId);

        if(!$DoctorService->puedeEvolucionar() && !$cliente->getAmbulatorioPresente()) {
            die('No puede evolucionar');
        }

        $evoluciones = $evolucionRepository->findByClienteYTipo($cliente, $tipoSeleccionado, $currentPage, $limit, $fechaDesde, $fechaHasta);
        

        $maxPages = ceil($evoluciones['paginator']->count() / $limit);
        

        return $this->render('evolucion/index.html.twig', [
            'nombreCliente'     => $cliente->getNombre() . ' ' . $cliente->getApellido(),
            'evolucions'        => $evoluciones['paginator'],
            'all_items'         => $evoluciones['query'],
            'clienteId'         => $cliente->getId(),
            'tipoSeleccionado'  => $tipoSeleccionado,
            'maxPages'          => $maxPages,
            'thisPage'          => $currentPage,
            'clientId'          => $clientId,
            'fechaDesde'        => $from,
            'fechaHasta'        => $to,
        ]);
    }

    /**
     * @Route("/new", name="evolucion_new", methods={"GET","POST"})
     */
    public function new(SluggerInterface $slugger, ValidatorInterface $validator, Request $request, ClienteRepository $clienteRepository, EvolucionRepository $evolucionRepository, DoctorRepository $doctorRepository): Response
    {
        $user = $this->getUser();
        $puedenEditarEvoluciones = in_array('ROLE_EDIT_HC', $user->getRoles());
        $doctores = $doctorRepository->findEmails();
        $docArr = [];
        foreach ( $doctores as $doc ) {
            $docArr[$doc['email']] = $doc['email'];
        }
        
        $error = '';
        if (!$user) {
            return $this->redirectToRoute('app_login');
        }
        $evolucion = new Evolucion();

        $cliente = $clienteRepository->find($request->get('cliente'));
        if($cliente->getDerivado() and !$puedenEditarEvoluciones) die('paciente derivado, no se puede evolucionar');
        //solo activos
        $evolucion->setPaciente($cliente);
        $evolucion->setUser($user->getEmail());
        $evolucion->setFecha(new \DateTime());

        $modalidades = $user->getModalidad();
        $modalidad = '';
        if( count($modalidades) === 1 ) {
            $modalidad = $modalidades[0];
        }

        $form = $this->createForm(EvolucionType::class, $evolucion, ['modalidad' => $modalidad, 'doctores' => $docArr, 'puedenEditarEvoluciones' => $puedenEditarEvoluciones]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

                $entityManager = $this->getDoctrine()->getManager();

                $adjuntos = $form->get('adjunto')->getData();
                
                if ($form->has('doctor')) {
                    $evolucion->setUser($form->get('doctor')->getData());
                }
                if(!empty($cliente->getFegreso()) && $cliente->getFegreso() < $evolucion->getFecha() && !$puedenEditarEvoluciones) {
                    die('paciente con fecha egreso anterior a la fecha de la evolución, no se puede evolucionar');
                }
                
                $hoy = new \DateTime();
                
                if ($evolucion->getFecha()->diff($hoy)->days > 0 && !$puedenEditarEvoluciones) {
                    die('la fecha de la evolución es anterior al día de la fecha, no se puede evolucionar');
                }
                
                foreach($adjuntos as $adjunto) {
                    $originalFilename = pathinfo($adjunto->getClientOriginalName(), PATHINFO_FILENAME);
                    $safeFilename = $slugger->slug($originalFilename);
                    $newFilename = $safeFilename.'-'.uniqid().'.'.$adjunto->guessExtension();

                    try {
                        $adjunto->move(
                            $this->getParameter('adjuntos_pacientes_directory') . '/' . $cliente->getId() . '/evoluciones/',
                            $newFilename
                        );
                    } catch (FileException $e) {
                        dd($e->getMessage());
                        // ... handle exception if something happens during file upload
                    }

                    $evolucion->addAdjuntoUrl($newFilename);
                }

                $entityManager->persist($evolucion);
                $entityManager->flush();

                return $this->redirectToRoute('evolucion_index', ['cliente' => $cliente->getId()], Response::HTTP_SEE_OTHER);

        } else {
            $errors = $validator->validate($form);
            if (!empty($errors[0])) {
                $error = $errors[0]->getMessage();
            }
        }

        return $this->render('evolucion/new.html.twig', [
            'evolucion' => $evolucion,
            'nombreCliente' => $cliente->getNombre() . ' ' . $cliente->getApellido(),
            'form' => $form->createView(),
            'clienteId' => $cliente->getId(),
            'error' => $error,
        ]);



    }

    /**
     * @Route("/{id}", name="evolucion_show", methods={"GET"})
     */
    public function show($id, EvolucionRepository $evolucionRepository): Response
    {
        $evolucion = $evolucionRepository->find($id);
        return $this->render('evolucion/show.html.twig', [
            'evolucion' => $evolucion,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="evolucion_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Evolucion $evolucion, DoctorRepository $doctorRepository): Response
    {
        $user = $this->getUser();
        $modalidades = $user->getModalidad();
        $usuarioActual = $evolucion->getUser();

        $modalidad = '';
        if( count($modalidades) === 1 ) {
            $modalidad = $modalidades[0];
        }

        $doctores = $doctorRepository->findEmails();
        $docArr = [];
        foreach ( $doctores as $doc ) {
            $docArr[$doc['email']] = $doc['email'];
        }

        $redirect = $request->get('redirect', '');

        $puedenEditarEvoluciones = in_array('ROLE_EDIT_HC', $user->getRoles());

        if ( $puedenEditarEvoluciones ) {
            $form = $this->createForm(EvolucionType::class, $evolucion, ['usuarioActual'=>$usuarioActual, 'modalidad' => $modalidad, 'doctores' => $docArr, 'puedenEditarEvoluciones' => $puedenEditarEvoluciones]);
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                $this->getDoctrine()->getManager()->flush();

                if($redirect !== '') {
                    return $this->redirect($redirect);
                } else {
                    return $this->redirectToRoute('cliente_historial', ['id' => $evolucion->getPaciente()->getId()], Response::HTTP_SEE_OTHER);
                }
            }

            return $this->render('evolucion/edit.html.twig', [
                'evolucion' => $evolucion,
                'clienteId' => $evolucion->getPaciente()->getId(),
                'form' => $form->createView(),
            ]);
        } else {
            return $this->redirectToRoute('cliente_historial', ['id' => $evolucion->getPaciente()->getId()], Response::HTTP_SEE_OTHER);
        }

    }

    /**
     * @Route("/{id}", name="evolucion_delete", methods={"POST"})
     */
    public function delete(Request $request, Evolucion $evolucion): Response
    {
        $clienteId = $evolucion->getPaciente()->getId();
        $redirect = $request->get('redirect', '');

        $puedenEditarEvoluciones = in_array('ROLE_EDIT_HC', $this->getUser()->getRoles());

        if( $puedenEditarEvoluciones ) {
            if ($this->isCsrfTokenValid('delete'.$evolucion->getId(), $request->request->get('_token'))) {

templates/evolucion/_delete_form.html.twig
<form method="post" action="{{ path('evolucion_delete', {'id': evolucion.id, 'redirect': app.request.headers.get('referer')}) }}" onsubmit="return confirm('Seguro desea borrar la evolución?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ evolucion.id) }}">
    <button class="btn btn-danger">Borrar</button>
</form>

templates/evolucion/_form.html.twig
{{ form_start(form) }}
<br>
<div class="form-row mb-4">
    <div class="col-sm">
        {{ form_label(form.tipo, 'Tipo') }}
        {{ form_widget(form.tipo) }}
    </div>
    {% if (is_granted('ROLE_EDIT_HC')) %}
    <div class="col-sm">
        {{ form_label(form.fecha, 'Fecha') }}
        {{ form_widget(form.fecha) }}
    </div>
    <div class="col-sm">
        {{ form_label(form.doctor, 'Doctor') }}
        {{ form_widget(form.doctor) }}
    </div>
    {% endif %}
</div>
<div class="form-row mb-4">
    <div class="col-sm">
        {{ form_label(form.description, 'Descripcion') }}
        {{ form_widget(form.description) }}
    </div>
</div>
<div class="form-row mb-4">
    <div class="col-sm">
        <button type="button" class="btn btn-action predeterminada">Se Realiza KTR.</button>
        <button type="button" class="btn btn-action predeterminada">Movilizacion. Elongacion. Motomed.</button>
        <button type="button" class="btn btn-action predeterminada">Estimulación Del Lenguaje Expresivo.</button>
        <button type="button" class="btn btn-action predeterminada">Se Aborda En T.O.</button>
    </div>
</div>
<div class="form-row">
    <div class="col-sm">
        {{ form_label(form.adjunto, 'Adjuntos') }}
        {{ form_widget(form.adjunto) }}
    </div>
</div>
<br>
<br>
<div class="form-group">
    {{ form_widget(form.save, {'attr': {'class': 'btn btn-primary'}}) }}
    <a class="btn btn-default" href="{{ app.request.headers.get('referer') }}">volver</a>
</div>
<br>

{{ form_end(form) }}

templates/evolucion/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Evolucion{% endblock %}

{% block body %}
    <h1>Edit Evolucion</h1>

    {{ include('evolucion/_form.html.twig', {'button_label': 'Update'}) }}

    {{ include('evolucion/_delete_form.html.twig') }}


{% endblock %}

templates/evolucion/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Evolucion index{% endblock %}

{% block body %}
    {% for message in app.flashes('info') %}
        <div class="alert alert-info">
            {{ message }}
        </div>
    {% endfor %}
    <h1>Evoluciones de {{ nombreCliente }}</h1>
    <div class="row">
        <div class="col-8 m-4">
            <form method="GET" action="{{ path('evolucion_index')}}">
                <input type="hidden" name="cliente" value="{{clientId}}">
                <input type="hidden" name="currentPage" value="1">
                <div class="row">
                    <div class="col-2">
                        <span>Tipo:</span>
                    </div> 
                    <div class="col-4">
                        <select class="form-control" name="tipoSeleccionado">
                            <option {% if tipoSeleccionado == 'todos'  %} selected {% endif %} value="todos">Todos</option>
                            <option {% if tipoSeleccionado == 'Nutricionista'  %} selected {% endif %} value='Nutricionista'>Nutricionista</option>
                            <option {% if tipoSeleccionado == 'Director medico'  %} selected {% endif %} value='Director medico'>Director medico</option>
                            <option {% if tipoSeleccionado == 'Sub director medico'  %} selected {% endif %} value='Sub director medico'>Sub director medico</option>
                            <option {% if tipoSeleccionado == 'Trabajadora social'  %} selected {% endif %} value='Trabajadora social'>Trabajadora social</option>
                            <option {% if tipoSeleccionado == 'Psiquiatra'  %} selected {% endif %} value='Psiquiatra'>Psiquiatra</option>
                            <option {% if tipoSeleccionado == 'Infectologo'  %} selected {% endif %} value='Infectologo'>Infectologo</option>
                            <option {% if tipoSeleccionado == 'Medico de guardia'  %} selected {% endif %} value='Medico de guardia'>Medico de guardia</option>
                            <option {% if tipoSeleccionado == 'Medico Clínico'  %} selected {% endif %} value='Medico Clínico'>Medico Clínico</option>
                            <option {% if tipoSeleccionado == 'Kinesiologo'  %} selected {% endif %} value='Kinesiologo'>Kinesiologo</option>
                            <option {% if tipoSeleccionado == 'Kinesiologo respiratorio'  %} selected {% endif %} value='Kinesiologo respiratorio'>Kinesiologo respiratorio</option>
                            <option {% if tipoSeleccionado == 'Terapista ocupacional'  %} selected {% endif %} value='Terapista ocupacional'>Terapista ocupacional</option>
                            <option {% if tipoSeleccionado == 'Fonoaudiologo'  %} selected {% endif %} value='Fonoaudiologo'>Fonoaudiologo</option>
                            <option {% if tipoSeleccionado == 'Psicologo'  %} selected {% endif %} value='Psicologo'>Psicologo</option>
                            <option {% if tipoSeleccionado == 'Fisiatra'  %} selected {% endif %} value='Fisiatra'>Fisiatra</option>
                            <option {% if tipoSeleccionado == 'Neurologo'  %} selected {% endif %} value='Neurologo'>Neurologo</option>
                            <option {% if tipoSeleccionado == 'Cardiologo'  %} selected {% endif %} value='Cardiologo'>Cardiologo</option>
                            <option {% if tipoSeleccionado == 'Urologo'  %} selected {% endif %} value='Urologo'>Urologo</option>
                            <option {% if tipoSeleccionado == 'Hematologo'  %} selected {% endif %} value='Hematologo'>Hematologo</option>
                            <option {% if tipoSeleccionado == 'Neumonologo'  %} selected {% endif %} value='Neumonologo'>Neumonologo</option>
                            <option {% if tipoSeleccionado == 'Cirujano'  %} selected {% endif %} value='Cirujano'>Cirujano</option>
                            <option {% if tipoSeleccionado == 'Traumatologo'  %} selected {% endif %} value='Traumatologo'>Traumatologo</option>
                            <option {% if tipoSeleccionado == 'Neumonologo'  %} selected {% endif %} value='Neumonologo'>Neumonologo</option>
                        </select>
                    </div>
                </div>
                <div class="row">
                    <div class="col-2">
                        <span>Desde:</span>
                    </div>
                    <div class="col-4">
                        <input class="form-control" type="date" name="from" value="{{fechaDesde}}">
                    </div>
                </div>
                <div class="row">
                    <div class="col-2">
                        <span>Hasta:</span>
                    </div>
                    <div class="col-4">
                        <input class="form-control" type="date" name="to" value="{{fechaHasta}}">
                    </div>
                    <div class="col-2">
                        <button class="btn btn-success"type="submit">buscar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="row" style="overflow-x: auto;">
        <table class="table mb-4">
        <thead>
            <tr>
                <th colspan="10">
                {% if maxPages > 1 %}
                    <nav aria-label="Page navigation example">
                        <ul class="pagination">
                            {% if thisPage > 1 %}
                                <li class="page-item" >
                                    <a class="page-link" href="{{ path('evolucion_index', {currentPage: (thisPage-1 < 1 ? 1 : thisPage-1),
                                                                            cliente: ((clientId) ? clientId : ''), 
                                                                            tipoSeleccionado: ((tipoSeleccionado) ? tipoSeleccionado : ''), 
                                                                            from: ((fechaDesde) ? fechaDesde : ''), 
                                                                            to: ((fechaHasta) ? fechaHasta : ''), 
                                            }) }}">«</a>
                                        </li>
                            {% endif %}

                            {# Render each page number #}
                            {% for i in 1..maxPages %}
                            <li class="page-item {% if thisPage == i %}active{% endif %}">
                                <a class="page-link" href="{{ path('evolucion_index', {
                                                                            currentPage: i, 
                                                                            cliente: ((clientId) ? clientId : ''), 
                                                                            tipoSeleccionado: ((tipoSeleccionado) ? tipoSeleccionado : ''), 
                                                                            from: ((fechaDesde) ? fechaDesde : ''), 
                                                                            to: ((fechaHasta) ? fechaHasta : ''), 
                                            }) 
                                        }}">
                                    {{ i }}
                                </a>
                            </li>
                            {% endfor %}

                            {# `»` arrow #}
                            {% if thisPage < maxPages %}
                                <li class="page-item">
                                    <a class="page-link" href="{{ path('cliente_historicos', {currentPage: (thisPage+1 <= maxPages ? thisPage+1 : thisPage),
                                                                                                    cliente: ((clientId) ? clientId : ''), 
                                                                                                    tipoSeleccionado: ((tipoSeleccionado) ? tipoSeleccionado : ''),
                                                                                                    from: ((fechaDesde) ? fechaDesde : ''), 
                                                                                                    to: ((fechaHasta) ? fechaHasta : ''), 
                                    }) }}">»</a>
                                </li>
                            {% endif %}
                        </ul>
                    </nav>
                {% endif %}
                </th>
            </tr>
            <tr>
            <tr>
                <th>Tipo</th>
                <th>Fecha</th>
                <th>Tiene adjuntos?</th>
                <th>Usuario</th>
            </tr>
        </thead>
        <tbody>
        {% for evolucion in evolucions %}
            <tr class="tr-link" data-link="{{ path('evolucion_show', {'id': evolucion.id}) }}">
                <th>{{ evolucion.tipo }}</th>
                <th>{{ evolucion.fecha ? evolucion.fecha|date('d/m/Y') : '' }}</th>
                {#<td>{{ evolucion.description|striptags|length > 25 ? evolucion.description|striptags|slice(0, 25) ~ '...' : evolucion.description|striptags }}</td>#}
                <td>
                    {% if evolucion.adjuntoUrl is not empty %}
                        <i class="fas fa-check"></i>
                    {% endif %}
                </td>
                <th>{{ evolucion.user }}</th>
            </tr>
            <tr>
                <td colspan="3">{{ evolucion.description | raw }}</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">Todavía no hay registros</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>
    <div class="row pb-4">
        <a href="{{ path('evolucion_new',  {'cliente': clienteId}) }}" class="btn btn-primary btn mr-2">Agregar Evolución</a>
        <a href="{{ path('doctor_historia') }}" class="btn btn-secondary btn">Volver</a>
    </div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script>
        $('.tr-link').click(function() {
            let url = $(this).data('link');
            window.location = url;
        });
    </script>
{% endblock %}

templates/evolucion/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Evoluciones{% endblock %}

{% block body %}
<div class="container">
    <div class="">
        <h1>Agregar Evolucion para {{ nombreCliente }}</h1>

        {{ include('evolucion/_form.html.twig') }}

    </div>

</div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script>
        {% if error is not empty %}
        alert("{{ error }}");
        {% endif %}
        $('.predeterminada').click(function (e) {
            let newHtml = $('#evolucion_description').val().length > 0 ? $('#evolucion_description').val() + ' ' + $(this).html() : $(this).html();
            CKEDITOR.instances['evolucion_description'].insertHtml(newHtml);
        });
    </script>
{% endblock %}

templates/evolucion/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Evolucion{% endblock %}

{% block body %}
    <h1>Evolucion</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Usuario</th>
                <td>{{ evolucion.user }}</td>
            </tr>
            <tr>
                <th>Tipo</th>
                <td>{{ evolucion.tipo }}</td>
            </tr>
            <tr>
                <th>Fecha</th>
                <td>{{ evolucion.fecha ? evolucion.fecha|date('d/m/Y') : '' }}</td>
            </tr>
            <tr>
                <th>Descripción</th>
                <td>{{ evolucion.description | raw }}</td>
            </tr>
            <tr>
                <th>Adjuntos</th>
                <td>
                    {% for url in evolucion.adjuntoUrl %}
                        <a href="{{ path('evolucion_get_adjunto',{'clienteId': evolucion.paciente.id, 'pdf': url}) }}" target="_blank">
                            {{ url|split('/')[0] }}
                        </a>
                        <br>
                    {% endfor %}
                </td>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="2"><a href="javascript:history.back();" class="btn btn-danger">Volver</a></td>
            </tr>
        </tfoot>
    </table>
{% endblock %}